<?php
/**
 * Company: Unleaded Group.
 * Developer: Jason Roy
 * Email: Jason@UnleadedGroup.com
 * Module: Unleaded_Jrewards
 */
date_default_timezone_set('America/New_York');
$date = date('m/d/Y');
?>

<div class="info-box rewards-box">

    <h2 class="legend" ><?php echo $this->__('REWARDS PROGRAM')?></h2>
    <?php echo $this
        ->getLayout()
        ->createBlock('cms/block')
        ->setBlockId('rewards-block')
        ->toHtml(); ?>
    <ul class="form-list">
        <li class="fields">
            <div class="field checkbox ">
                <input
                    type="checkbox"
                    name="jackrabbit-signup"
                    id="jackrabbit-signup"
                    title="<?php echo Mage::helper('core')
                        ->quoteEscape($this->__('Sign Up')) ?>"
                    class="checkbox" />
                <label
                    for="jackrabbit-signup"
                    class="big-title">
                    <?php echo $this->__('Yes, Sign Me Up!') ?>
                    <span><?php echo $this->__('effective ' . $date) ?></span><br/>
                    <span> <?php echo $this->__('I Agree to the run rewards program 
                        <a 
                            href="/info/run-rewards-terms-conditions" 
                            target="_blank">
                            terms and conditions
                        </a>') ?>
                    </span>
                </label>
            </div>
        </li>
    </ul>
    <div class="no-display reward-field-section" id="rewards-information">
        <h2 class="legend" ><?php echo $this->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li id="home-phone-rewards">
                <div class="field">
                    <label for="home-phone">
                        <?php echo $this->__('Home Phone Number') ?>
                    </label>
                    <div class="input-box">
                        <input
                            type="text"
                            name="home-phone"
                            id="home-phone"
                            title="<?php echo Mage::helper('core')
                                ->quoteEscape($this->__('Home-Phone')) ?>"
                            value=""
                            class="input-text validate-phoneLax" />
                    </div>
                </div>
            </li>
            <li class="fields no-display" id="cellphone-rewards">
                <div class="field">
                    <label for="cell-phone">
                        <?php echo $this->__('Cell Phone') ?>
                    </label>
                    <div class="input-box">
                        <input
                            type="text"
                            name="cell-phone"
                            id="cell-phone"
                            title="<?php echo Mage::helper('core')
                                ->quoteEscape($this->__('Cell-Phone')) ?>"
                            value=""
                            class="input-text validate-phoneLax" />
                    </div>
                </div>
            </li>
            <li class="custom-field">
                <h5><?php echo $this->__('Text Messaging') ?></h5>
                <div class="field">

                    <input
                        class="radio"
                        type="radio"
                        name="text-messaging"
                        id="accept-text-messaging"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Accept')) ?>"
                        value="1"
                    />
                    <label
                        for="accept-text-messaging"><?php echo $this->__('Accept') ?>
                        <span>
                            <em>*</em> <?php echo $this->__('Standard messaging and data rates may apply') ?>
                        </span>
                    </label>

                </div>
            </li>
            <li class="custom-field">
                <div class="field">
                    <input
                        class="radio"
                        type="radio"
                        name="text-messaging"
                        id="decline-text-messaging"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Decline')) ?>"
                        value="0"
                    />
                    <label for="decline-text-messaging"><?php echo $this->__('Decline') ?></label>
                </div>
            </li>
        </ul>
        
    </div>

</div>
<script type="text/javascript">
    jQuery(document).ready(function ($){
        $('#jackrabbit-signup').change(function(){
            if($(this).is(":checked")) {
                jQuery("#rewards-information").removeClass("no-display");
            } else {
                jQuery("#rewards-information").addClass("no-display");
            }
        });

        $('#accept-text-messaging').change(function(){
            if($(this).is(":checked")) {
                jQuery("#cellphone-rewards").removeClass("no-display");
                jQuery("#cellphone-rewards").find("#cell-phone").addClass("required-entry");

            }
        });

        $('#decline-text-messaging').change(function(){
            if($(this).is(":checked")) {
                jQuery("#cellphone-rewards").addClass("no-display");
                jQuery("#cellphone-rewards").find("#cell-phone").removeClass("required-entry");

            }
        });
    });
</script>
